#[[main]]
#name = "Accueil"
#url = "/"
#weight = 1

[[main]]
name = "A Propos"
url = "/about/"
weight = 10

[[main]]
name = "Productions"
url = "/blog/"
weight = 20

#[[main]]
#name = "Productions"
#url = "/projects/"
#weight = 30

#[[main]]
#name = "Mariage"
#url = "/projects/mariage/"
#parent = "Productions"
#weight = 1

#[[main]]
#name = "Evenement"
#url = "/projects/evenement/"
#parent = "Productions"
#weight = 2

#[[main]]
#name = "Interview"
#url = "/projects/interview/"
#parent = "Productions"
#weight = 3

#[[main]]
#name = "Entreprise"
#url = "/projects/entreprise/"
#parent = "Productions"
#weight = 4

#[[main]]
#name = "Projets"
#url = "/galery/"
#weight = 35

[[main]]
name = "Contact"
url = "/contact/"
weight = 36

#[[main]]
#name = "Tags"
#url = "/tags/"
#weight = 40

#[[social]]
#name = "LinkedIn"
#pre = "<i class=\"fab fa-linkedin fa-2x\"></i>"
#url = "https://linkedin.com/"
#weight = 10

#[[social]]
#name = "GitHub"
#pre = "<i class=\"fab fa-github fa-2x\"></i>"
#url = "https://github.com/"
#weight = 20

#[[social]]
#name = "Medium"
#pre = "<i class=\"fab fa-medium fa-2x\"></i>"
#url = "https://medium.com/"
#weight = 30

#[[sample]]
#name = "Blog"
#url = "/blog/"
#weight = 10

[[sample]]
name = "Projects"
url = "/projects/"
weight = 20

[[sample]]
name = "Sample project"
url = "/projects/sample-project/"
parent = "Projects"
weight = 1

[[sample]]
name = "Another project"
url = "/projects/another-project/"
parent = "Projects"
weight = 2